image: microsoft/dotnet:latest

stages:
    - build
    - test
    - deploy

variables:
    test: "DemoTests"
    SAST_DISABLE_DIND: "false"

include:
  - template: SAST.gitlab-ci.yml

build:
    stage: build
    before_script:
    - "cd Demo"
    - "dotnet restore"
    script:
        - "dotnet build"
    artifacts:
        paths:
        - ./

test:
    stage: test
    artifacts:
    before_script:
    - "cd DemoTests"
    - "dotnet restore"
    script: 
        - "dotnet test"
        
deploy:
  stage: deploy
  image: microsoft/azure-cli
  dependencies:
    - build
  script:
    - az storage blob delete-batch -s "\$web" --connection-string $AZURE_STORAGE_CONNECTION_STRING
    - az storage blob upload-batch -d "\$web" -s ./ --connection-string $AZURE_STORAGE_CONNECTION_STRING
  only:
    - master
---
metrics:
  script:
    - echo 'metric_name metric_value' > metrics.txt
  artifacts:
    reports:
      metrics: metrics.txt

---

stages:
  - iac_validate
  - iac_plan
  - iac_apply

default:
  image:
    name: hashicorp/terraform:latest
    entrypoint:
      ["/bin/sh", "-c"]
  before_script:
    - terraform init
  cache:
    key: terraform
    paths:
      - .terraform

terraform_validate:
  stage: iac_validate
  script:
    - terraform validate
  except:
    refs:
      - master

terraform_plan:
  stage: iac_plan
  script: 
    - terraform plan --out plan
  only:
    refs:
      - master
  artifacts:
    paths:
      - plan

terraform_apply:
  stage: iac_apply
  script:
    - terraform apply --auto-approve plan
  when: manual
  allow_failure: false
  only:
    refs:
      - master
