image: microsoft/dotnet:latest

stages:
    - build
    - test
    - deploy

variables:
    test: "DemoTests"
    SAST_DISABLE_DIND: "false"

include:
  - template: SAST.gitlab-ci.yml

build:
    stage: build
    before_script:
    - "cd Demo"
    - "dotnet restore"
    artifacts:
        paths:
          - "./"
        scripts:
          - "dotnet build"
        only:
          - master

test:
    stage: test
    artifacts:
    before_script:
    - "cd DemoTests"
    - "dotnet restore"
    script: 
        - "dotnet test"
        
deploy:
  stage: deploy
  image: microsoft/azure-cli
  dependencies:
    - build
  script:
    - az storage blob delete-batch -s "\$web" --connection-string $AZURE_STORAGE_CONNECTION_STRING
    - az storage blob upload-batch -d "\$web" -s ./ --connection-string $AZURE_STORAGE_CONNECTION_STRING
  only:
    - master
