image: microsoft/dotnet:latest

stages:
    - build
    - test
    - deploy

variables:
    test: "DemoTests"
    SAST_DISABLE_DIND: "false"

include:
  - template: SAST.gitlab-ci.yml

build:
    stage: build
    before_script:
    - "cd Demo"
    - "dotnet restore"
    script:
        - "dotnet build"

test:
    stage: test
    artifacts:
    before_script:
    - "cd DemoTests"
    - "dotnet restore"
    script: 
        - "dotnet test"
        
deploy:
  stage: deploy
  image: microsoft/azure-cli
  dependencies:
    - test
  script:
    - az storage blob delete-batch -s "\$web" --connection-string $AZURE_STORAGE_CONNECTION_STRING
    - az storage blob upload-batch -d "\$web" -s build --connection-string $AZURE_STORAGE_CONNECTION_STRING
  only:
    - master
