image: microsoft/dotnet:latest

stages:
    - build
    - test

variables:
    test: "DemoTests"



build:
    stage: build
    before_script:
    - "cd Demo"
    - "dotnet restore"
    script:
        - "dotnet build"

test:
    stage: test
    before_script:
    - "cd DemoTests"
    - "dotnet restore"
    script: 
        - "dotnet test"
